<a href="https://colab.research.google.com/github/prayantgupta15/DataEngineering/blob/main/myFirstLab.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
print("Hello")

Hello


In [ ]:
!pip install numpy

In [3]:
import numpy as np

In [ ]:
np

<module 'numpy' from '/usr/local/lib/python3.10/dist-packages/numpy/__init__.py'>

In [ ]:
lst = [1,2,3]
print(type(lst))

<class 'list'>


In [ ]:
arr= np.array(lst)

In [ ]:
print(arr)

[1 2 3]


In [ ]:
print(type(arr))

<class 'numpy.ndarray'>


In [ ]:
import numpy as np

In [ ]:
np

<module 'numpy' from '/usr/local/lib/python3.10/dist-packages/numpy/__init__.py'>

In [ ]:
type(np)

module

In [ ]:
lst = [1,2,3]

In [ ]:
nplst = np.array(lst)
nplst

array([1, 2, 3])

In [ ]:
nplst.ndim

1

In [ ]:
nplst.shape

(3,)

In [ ]:
sq = [
    [1,2,3],
    [1,2,3]
]
sq = np.array(sq)
sq.shape

(2, 3)

In [ ]:
sq.ndim

2

In [ ]:
z = np.zeros((2,3))

In [ ]:
z

array([[0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
one = np.random.random()
one

0.16891286953662077

In [ ]:
arr  = np.random.random((2,3))
arr

array([[0.64242864, 0.22842604, 0.37922994],
       [0.63790185, 0.73456288, 0.99225896]])

In [ ]:
arr.reshape((3,2))

array([[0.64242864, 0.22842604],
       [0.37922994, 0.63790185],
       [0.73456288, 0.99225896]])

In [ ]:
arr = np.arange(1,10,1)
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
arr = np.linspace(1,10,9)
arr

array([ 1.   ,  2.125,  3.25 ,  4.375,  5.5  ,  6.625,  7.75 ,  8.875,
       10.   ])

In [13]:
arr1 = np.arange(1,5,1)
arr1 = arr1+1
arr1

array([2, 3, 4, 5])

In [21]:
s = arr1.sum()
print("sum:",s)
maxVal = arr1.max()
print("maxVal:",maxVal)

minVal = arr1.min()
print("min:",minVal)

sum: 14
maxVal: 5
min: 2


In [4]:
arr_2d = np.random.randint(10,size=(3,3))
print(arr_2d)
print(arr_2d+1)
cols_max = arr_2d.max(axis=0)
print(cols_max)

rows_max = arr_2d.max(axis=1)
print(rows_max)

[[8 6 1]
 [1 7 7]
 [8 7 0]]
[[9 7 2]
 [2 8 8]
 [9 8 1]]
[8 7 7]
[8 7 8]


In [5]:
arr_2d_1 = arr_2d
arr_2d_2 = arr_2d + 1
print(arr_2d_2)
print(arr_2d_1+arr_2d_2)
print(arr_2d_1*arr_2d_1)

[[9 7 2]
 [2 8 8]
 [9 8 1]]
[[17 13  3]
 [ 3 15 15]
 [17 15  1]]
[[64 36  1]
 [ 1 49 49]
 [64 49  0]]


In [23]:
arr = np.random.randint(10,size=(5,6))
print(arr)
print("slice",arr[2:,2:])
# print(arr*arr_2d_1)
# np.sort(a=arr,axis=1,kind='mergesort')

np.sort(a=arr,axis=0,kind='mergesort')
# print("\n")
# print(arr)

[[2 8 1 8 9 1]
 [9 0 4 4 7 1]
 [3 3 8 8 5 0]
 [2 9 8 3 3 8]
 [3 7 8 4 9 4]]
slice [[8 8 5 0]
 [8 3 3 8]
 [8 4 9 4]]


array([[2, 0, 1, 3, 3, 0],
       [2, 3, 4, 4, 5, 1],
       [3, 7, 8, 4, 7, 1],
       [3, 8, 8, 8, 9, 4],
       [9, 9, 8, 8, 9, 8]])