<a href="https://colab.research.google.com/github/prayantgupta15/DataEngineering/blob/main/myFirstLab.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
print("Hello")

Hello


In [ ]:
!pip install numpy

In [3]:
import numpy as np

In [ ]:
np

<module 'numpy' from '/usr/local/lib/python3.10/dist-packages/numpy/__init__.py'>

In [ ]:
lst = [1,2,3]
print(type(lst))

<class 'list'>


In [ ]:
arr= np.array(lst)

In [ ]:
print(arr)

[1 2 3]


In [ ]:
print(type(arr))

<class 'numpy.ndarray'>


In [1]:
import numpy as np

In [2]:
np

<module 'numpy' from '/usr/local/lib/python3.10/dist-packages/numpy/__init__.py'>

In [3]:
type(np)

module

In [4]:
lst = [1,2,3]

In [5]:
nplst = np.array(lst)
nplst

array([1, 2, 3])

In [8]:
nplst.ndim

1

In [9]:
nplst.shape

(3,)

In [13]:
sq = [
    [1,2,3],
    [1,2,3]
]
sq = np.array(sq)
sq.shape

(2, 3)

In [14]:
sq.ndim

2

In [16]:
z = np.zeros((2,3))

In [17]:
z

array([[0., 0., 0.],
       [0., 0., 0.]])

In [16]:
one = np.random.random()
one

0.16891286953662077

In [7]:
arr  = np.random.random((2,3))
arr

array([[0.64242864, 0.22842604, 0.37922994],
       [0.63790185, 0.73456288, 0.99225896]])

In [8]:
arr.reshape((3,2))

array([[0.64242864, 0.22842604],
       [0.37922994, 0.63790185],
       [0.73456288, 0.99225896]])

In [9]:
arr = np.arange(1,10,1)
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
arr = np.linspace(1,10,9)
arr

array([ 1.   ,  2.125,  3.25 ,  4.375,  5.5  ,  6.625,  7.75 ,  8.875,
       10.   ])