<a href="https://colab.research.google.com/github/prayantgupta15/DataEngineering/blob/main/myFirstLab.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
print("Hello")

Hello


In [ ]:
!pip install numpy

In [1]:
import numpy as np

In [ ]:
np

<module 'numpy' from '/usr/local/lib/python3.10/dist-packages/numpy/__init__.py'>

In [ ]:
lst = [1,2,3]
print(type(lst))

<class 'list'>


In [ ]:
arr= np.array(lst)

In [ ]:
print(arr)

[1 2 3]


In [ ]:
print(type(arr))

<class 'numpy.ndarray'>


In [ ]:
import numpy as np

In [ ]:
np

<module 'numpy' from '/usr/local/lib/python3.10/dist-packages/numpy/__init__.py'>

In [ ]:
type(np)

module

In [ ]:
lst = [1,2,3]

In [ ]:
nplst = np.array(lst)
nplst

array([1, 2, 3])

In [ ]:
nplst.ndim

1

In [ ]:
nplst.shape

(3,)

In [ ]:
sq = [
    [1,2,3],
    [1,2,3]
]
sq = np.array(sq)
sq.shape

(2, 3)

In [ ]:
sq.ndim

2

In [ ]:
z = np.zeros((2,3))

In [ ]:
z

array([[0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
one = np.random.random()
one

0.16891286953662077

In [ ]:
arr  = np.random.random((2,3))
arr

array([[0.64242864, 0.22842604, 0.37922994],
       [0.63790185, 0.73456288, 0.99225896]])

In [ ]:
arr.reshape((3,2))

array([[0.64242864, 0.22842604],
       [0.37922994, 0.63790185],
       [0.73456288, 0.99225896]])

In [ ]:
arr = np.arange(1,10,1)
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
arr = np.linspace(1,10,9)
arr

array([ 1.   ,  2.125,  3.25 ,  4.375,  5.5  ,  6.625,  7.75 ,  8.875,
       10.   ])

In [13]:
arr1 = np.arange(1,5,1)
arr1 = arr1+1
arr1

array([2, 3, 4, 5])

In [21]:
s = arr1.sum()
print("sum:",s)
maxVal = arr1.max()
print("maxVal:",maxVal)

minVal = arr1.min()
print("min:",minVal)

sum: 14
maxVal: 5
min: 2


In [4]:
arr_2d = np.random.randint(10,size=(3,3))
print(arr_2d)
print(arr_2d+1)
cols_max = arr_2d.max(axis=0)
print(cols_max)

rows_max = arr_2d.max(axis=1)
print(rows_max)

[[7 5 9]
 [2 0 7]
 [5 9 2]]
[[ 8  6 10]
 [ 3  1  8]
 [ 6 10  3]]
[7 9 9]
[9 7 9]


In [5]:
arr_2d_1 = arr_2d
arr_2d_2 = arr_2d + 1
print(arr_2d_2)
print(arr_2d_1+arr_2d_2)
print(arr_2d_1*arr_2d_1)

[[ 8  6 10]
 [ 3  1  8]
 [ 6 10  3]]
[[15 11 19]
 [ 5  1 15]
 [11 19  5]]
[[49 25 81]
 [ 4  0 49]
 [25 81  4]]


In [2]:
arr = np.random.randint(10,size=(5,6))
print(arr)
print("slice",arr[2:,2:])
# print(arr*arr_2d_1)
# np.sort(a=arr,axis=1,kind='mergesort')

np.sort(a=arr,axis=0,kind='mergesort')
# print("\n")
# print(arr)

[[2 8 0 9 0 6]
 [7 4 3 7 8 6]
 [2 5 1 0 2 0]
 [6 4 0 1 0 7]
 [1 6 6 4 7 1]]
slice [[1 0 2 0]
 [0 1 0 7]
 [6 4 7 1]]


array([[1, 4, 0, 0, 0, 0],
       [2, 4, 0, 1, 0, 1],
       [2, 5, 1, 4, 2, 6],
       [6, 6, 3, 7, 7, 6],
       [7, 8, 6, 9, 8, 7]])

In [8]:
# join 2 arrays
short_arr=arr[2:,3:]
np.vstack((arr_2d_2,short_arr))


array([[ 8,  6, 10],
       [ 3,  1,  8],
       [ 6, 10,  3],
       [ 0,  2,  0],
       [ 1,  0,  7],
       [ 4,  7,  1]])

In [9]:
np.hstack((arr_2d_2,short_arr))


array([[ 8,  6, 10,  0,  2,  0],
       [ 3,  1,  8,  1,  0,  7],
       [ 6, 10,  3,  4,  7,  1]])

In [10]:
np.concatenate((arr_2d_2,short_arr),axis=0)

array([[ 8,  6, 10],
       [ 3,  1,  8],
       [ 6, 10,  3],
       [ 0,  2,  0],
       [ 1,  0,  7],
       [ 4,  7,  1]])

In [14]:
harr= np.concatenate((arr_2d_2,short_arr),axis=1)
print(harr)

[[ 8  6 10  0  2  0]
 [ 3  1  8  1  0  7]
 [ 6 10  3  4  7  1]]


In [19]:
np.hsplit(harr,6)

[array([[8],
        [3],
        [6]]),
 array([[ 6],
        [ 1],
        [10]]),
 array([[10],
        [ 8],
        [ 3]]),
 array([[0],
        [1],
        [4]]),
 array([[2],
        [0],
        [7]]),
 array([[0],
        [7],
        [1]])]